- contracts/bond/Bond.sol
- contracts/bond/BondFactory.sol
- package.json
- test/bond-factory.test.ts
- test/bond.test.ts
- test/utils/contracts.ts
- test/utils/events.ts
- test/utils/transaction.ts
Introducing the first iteration for the Bond contract!
A Bond contract allows a number of guarantors to deposit a security token (e.g. BIT) in exchange for a debt token (i.e. a new ERC20 token). The debt token can then be trade and used for further collateralised & derivatives.
Outside of the Bond contract's awareness the bond may be used for other purposes (such as securing a loan from a BitDAO linked treasury).
A Bond contract needs to support slashing and withdrawal of the original security token in exchange for the issued debt tokens. The address redeeming the debt may not be the one who was originally issued it (as transfers can happen).
Plant UML sequence diagram covering the Bonding contract use cases: https://github.com/windranger-io/windranger-treasury/blob/main/docs/specs/bonding …
> feat: bonding contract

- contracts/bond/Bond.sol
- contracts/bond/BondFactory.sol
- test/bond-factory.test.ts
- test/bond.test.ts
- test/utils/events.ts
closes https://github.com/windranger-io/windranger-treasury/issues/24
> chore: renaming to align with similar external products

- docs/specs/bonding.puml
> spec: no contract self-destruct on full slash

- contracts/bond/Bond.sol
`private` helper functions that get inlined (no additional gas cost) to help with code readability / understandability.
Closes https://github.com/windranger-io/windranger-treasury/issues/30
> chore: helper functions to improve readability

- contracts/bond/Bond.sol
Also remedies this medium level Slither linter warning.
```
Bond._redemptionAmount(uint256,uint256) (contracts/bond/Bond.sol#286-298) performs a multiplication on the result of a division:
-redemptionRatio = (DECIMAL_OFFSET * _guarantorCollateral) / totalSupply (contracts/bond/Bond.sol#294-295)
-(redemptionRatio * amount) / DECIMAL_OFFSET (contracts/bond/Bond.sol#296)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply
```
There is not an issue, as the warning is actually being solved by the `DECIMAL_OFFSET` which is the accuracy for the redemption ratio.
> fix: fewer math operation on slashing redemption

- test/bond-factory.test.ts
- test/bond.test.ts
- test/utils/contracts.ts
> fix: adding generics to the contract handling in the test framework

- .github/dependabot.yml
> ci: dependabot monthly cadence

- .github/workflows/master-push-pull.yml
> ci: slither analyzer as PR status check

- .github/workflows/master-push-pull.yml
Split the TS linting from the testing and named the jobs.
> ci: job names

- .github/workflows/master-push-pull.yml
> ci: github action cache actually caching

- .github/dependabot.yml
> ci: longer cadence between update checks

- contracts/bond/Bond.sol
As a result of the static analyser Slither recommended changes, the events emitted by the contract were moved to before external contract calls. This has resulted in jumbled event ordering, in the context of all the events emitted by a transaction (including those emitted by the parent and external).
Deposit events before this PR 
``` 
transfer [ERC20 parent]
deposit [Bond]
transfer (ERC20 collateral]
```
Deposit events after this PR 
``` 
deposit [Bond]
transfer [ERC20 parent]
transfer (ERC20 collateral]
```
This PR moves the events of the Bond contract to be emitted before any of the ERC20 parent events, and external contract.
> fiX: emitting events preceding all their implementation events

- .gitignore
- README.md
Two options to install Slither, either locally or via Docker container.
Both options run successfully locally (lots of containers & volumes to clean up with the Docker option tho 🤷 )
> docs: slither run instructions

- test/bond.test.ts
Linting warnings flagged for unread variables.
> chore: removing assignment to unread variables

- .github/workflows/master-push-pull.yml
> chore: consistent whitespace in step name

- contracts/bond/Bond.sol
- test/bond.test.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/82
> fix: initial debt tokens field

- contracts/bond/Bond.sol
- contracts/bond/BondFactory.sol
- test/bond-factory.test.ts
- test/bond.test.ts
- test/utils/events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/67
> fix: data field for external apps

- test/bond.test.ts
> chore: suffix of tokens for an erc20

- contracts/bond/Bond.sol
- test/bond.test.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/58
> fix: public getter for has full collateral

- .github/workflows/master-push-pull.yml
- contracts/bond/BondFactory.sol
- contracts/test/Box.sol
- test/bond-factory.test.ts
- test/bond.test.ts
- test/utils/events.ts
Adds collateral whitelisting and management in the BondFactory.
Closes https://github.com/windranger-io/windranger-treasury/issues/52
> feat: collateral whitelist

- contracts/bond/Bond.sol
- contracts/bond/BondFactory.sol
- contracts/bond/ExpiryTimestamp.sol
- package-lock.json
- test/bond-factory.test.ts
- test/bond.test.ts
- test/utils/events.ts
closes https://github.com/windranger-io/windranger-treasury/issues/57
> feat: expiry guarded function to move collateral to treasury

- .github/workflows/master-push-pull.yml
- .lintstagedrc
- .solhint.json
- .solhintignore
- package-lock.json
- package.json
> fix: solhint

- contracts/bond/Bond.sol
- contracts/bond/Redeemable.sol
Single responsibility principle.
> fix: refactoring redeemable into an abstract contract

- contracts/bond/BondFactory.sol
- contracts/bond/CollateralWhitelist.sol
- contracts/bond/Redeemable.sol
- test/bond-factory.test.ts
Single Responsibility principle.
> fix: abstract the collateral whitelist from BondFactory

- contracts/bond/BondFactory.sol
- contracts/bond/CollateralWhitelist.sol
- test/bond-factory.test.ts
Adding a remove function guarded by `onlyOwner` to remove an entry from the list of acceptable collateral.
> fix: remove from whitelist

- contracts/bond/BondFactory.sol
- test/bond-factory.test.ts
> fix: BondFactory permission ut

- contracts/bond/Bond.sol
- test/bond.test.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/59
> feat: knowledge of slashing

- contracts/bond/Bond.sol
Keeping the prefix and suffixes of field names consistent.
> fix: consistency in variable naming

- .github/CODEOWNERS
> ci: devops owns github directory

- contracts/bond/ExpiryTimestamp.sol
> fix: doc to warn of intentional time usage

- test/bond-factory.test.ts
- test/bond.test.ts
- test/contracts/bond/bond-events.ts
- test/contracts/bond/verify-bond-events.ts
- test/contracts/bond/verify-bond-factory-events.ts
- test/framework/events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/17
> Events shared name

- .lintstagedrc
> fix: formatting sol files as solhint does not

- test/contracts/bond/verify-bond-events.ts
> fix: redundant async

- contracts/bond/Bond.sol
- contracts/bond/BondFactory.sol
- contracts/bond/CollateralWhitelist.sol
- contracts/bond/ExpiryTimestamp.sol
- contracts/bond/Redeemable.sol
Update the contents of the Solidity inline docs and update to the dev team agreed format.
```
/**
* @notice Top level description
*
* @dev deets
*/
```
Closes https://github.com/windranger-io/windranger-treasury/issues/73
> docs: natspec

- .openzeppelin/unknown-33133.json
- contracts/bond/Bond.sol
Quicker to grep than many zerroes
> fix: exponent notation

- .openzeppelin/unknown-33133.json
- contracts/bond/Bond.sol
- contracts/bond/BondFactory.sol
- test/bond-factory.test.ts
- test/bond.test.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/83
> feat: Minimum bond holding

- contracts/bond/Bond.sol
- contracts/bond/MetaDataStore.sol
- test/bond.test.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/133
> feat: metadata bucket

- config/logging.ts
- contracts/bond/BondFactory.sol
- contracts/bond/BondManager.sol
- hardhat.config.ts
- package-lock.json
- package.json
- scripts/create-bond.ts
- scripts/deploy.ts
Simple deploy of non-proxy contracts for Rinkeby, used to drive development of SubGraph handlers and data model (used by front end)
> feat: deploy scripts

- contracts/bond/BondFactory.sol
- contracts/bond/BondManager.sol
- contracts/bond/BondMediator.sol
- test/bond-factory.test.ts
- test/bond-manager.test.ts
- test/bond-mediator.test.ts
- test/contracts/roles.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/165
> fix: access control tests

- contracts/bond/BondCreator.sol
- contracts/bond/BondCurator.sol
- contracts/bond/BondFactory.sol
- contracts/bond/BondManager.sol
- contracts/bond/BondMediator.sol
- contracts/bond/ERC20SingleCollateralBond.sol
- contracts/bond/ExpiryTimestamp.sol
- test/bond-manager.test.ts
- test/bond-mediator.test.ts
- test/contracts/bond/bond-manager-events.ts
- test/contracts/bond/verify-manager-events.ts
- test/contracts/bond/verify-single-collateral-bond-events.ts
- test/contracts/ownable/ownable-events.ts
- test/contracts/ownable/verify-ownable-event.ts
- test/erc20-single-collateral-bond.test.ts
- test/framework/event-logs.ts
- test/framework/verify.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/147
> fix: mediator and manager fixes and tests

- README.md
> fix: case correction to Windranger

- contracts/bond/BondFactory.sol
- contracts/bond/BondManager.sol
- contracts/bond/BondMediator.sol
- contracts/bond/ERC20SingleCollateralBond.sol
- scripts/versioning/check-contracts.ts
As per
https://github.com/windranger-io/windranger-treasury/issues/184
Inherit the Version contract where applicable and run the check to ensure the bytecode matches the git tag in the github workflow. 
Todo:
- where else does Version need to be inherited?
> feat: inherit Version for Bond contracts and add check to workflow script

- .solhintignore
> fix: updating solhint ignore

- test/bond-access-control.test.ts
- test/bond-factory.test.ts
- test/bond-manager.test.ts
- test/bond-mediator.test.ts
> fix: removing unused vars

- contracts/bond/BondCreator.sol
- contracts/bond/BondCurator.sol
Design wise, these two contract are really interfaces (they contain no state or function implementations).
> fix: interface over abstract contract

- .prettierignore
> ci: ignoring more during prettier pass

- contracts/bond/BondFactory.sol
- contracts/bond/BondManager.sol
- contracts/bond/BondMediator.sol
- test/bond-factory.test.ts
- test/bond-mediator.test.ts
> feat: inherit PausableUpgradable

- contracts/bond/BondMediator.sol
- contracts/bond/CollateralWhitelist.sol
- test/bond-mediator.test.ts
Part three of nine in the PR set for https://github.com/windranger-io/windranger-treasury/issues/161
> feat: collateral symbol to tokens address

- contracts/bond/BondMediator.sol
- contracts/bond/BondPortal.sol
- test/bond-mediator.test.ts
- test/contracts/bond/bond-creator-events.ts
- test/contracts/bond/bond-curator-events.ts
- test/contracts/bond/bond-portal-events.ts
Part four of nine for the DAO config refactoring, creating the DaoConfig struct and putting the treasury in it
> feat: bond dao config struct

- contracts/bond/BondMediator.sol
- contracts/bond/CollateralWhitelist.sol
- test/bond-mediator.test.ts
> feat: Use set for whitelist

- contracts/bond/BondCurator.sol
- contracts/bond/BondManager.sol
- contracts/bond/BondMediator.sol
- test/bond-manager.test.ts
- test/bond-mediator.test.ts
Adding the DAO ID mapping into the BondManager, part of the https://github.com/windranger-io/windranger-treasury/issues/161 refactoring
> feat: dao aware bond manager

- contracts/bond/BondMediator.sol
- contracts/bond/DaoBondCollateralWhitelist.sol
- contracts/bond/DaoBondConfiguration.sol
- contracts/test/bond/DaoBondConfigurationBox.sol
- test/bond-mediator.test.ts
- test/dao-bond-collateral-whitelist.test.ts
- test/dao-bond-configuration.test.ts
Consistent function naming across the Dao Bond Config functions, part of https://github.com/windranger-io/windranger-treasury/issues/161
> fix: dao collateral whitelist naming

- contracts/bond/BondMediator.sol
Closes https://github.com/windranger-io/windranger-treasury/issues/227
> fix: init pauseable

- contracts/bond/BondAccessControl.sol
- contracts/bond/DaoBondCollateralWhitelist.sol
- contracts/bond/DaoBondConfiguration.sol
- contracts/bond/ExpiryTimestamp.sol
- contracts/bond/MetaDataStore.sol
- contracts/bond/Redeemable.sol
- contracts/sweep/SweepERC20.sol
- contracts/sweep/SweepERC721.sol
- contracts/sweep/TokenSweep.sol
- contracts/test/SweepERC20TokensHarness.sol
- contracts/test/SweepERC721TokensHarness.sol
- slither.json
Closes https://github.com/windranger-io/windranger-treasury/issues/222
> fix: enabling slither naming convention detector

- .github/dependabot.yml
> fix: dependabot replaced by renovate

- contracts/bond/DaoBondCollateralWhitelist.sol
- test/bond-mediator.test.ts
- test/contracts/bond/verify-whitelist-events.ts
- test/contracts/bond/whitelist-events.ts
- test/dao-bond-collateral-whitelist.test.ts
> feat: add whitelist events

- contracts/bond/RoleAccessControl.sol
- test/role-access-control.test.ts
> fix: access control query support

- scripts/utils/environment-variable.ts
> fix: unused import

- README.md
- hardhat.config.ts
- package-lock.json
- package.json
Need to know the size of the `BondFactory` that is exceeding the limit ...adding a task to display the contract sizes.
> feat: contract sizing task

- contracts/bond/BondCreator.sol
- contracts/bond/BondFactory.sol
- contracts/bond/BondMediator.sol
- contracts/bond/BondPortal.sol
- contracts/bond/ERC20SingleCollateralBond.sol
- contracts/bond/SingleCollateralMultiRewardBond.sol
- contracts/bond/TimeLockMultiRewardBond.sol
- contracts/test/bond/ERC20SingleCollateralBondBox.sol
- contracts/test/bond/TimeLockMultiRewardBondBox.sol
- scripts/deploy/bond-deploy-no-etherscan.ts
- scripts/deploy/bond-deploy.ts
- scripts/utils/contract.ts
- test/framework/contracts.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/263
> fix: calldata in parameters, no logging in it

- contracts/bond/BondCreator.sol
- contracts/bond/BondCurator.sol
- contracts/bond/BondPortal.sol
- contracts/bond/ERC20SingleCollateralBond.sol
- contracts/bond/RoleMembership.sol
- contracts/bond/TimeLockMultiRewardBond.sol
Closes https://github.com/windranger-io/windranger-treasury/issues/260
> fix: indexing of events

- contracts/bond/ERC20SingleCollateralBond.sol
- scripts/deploy/bitdao-deploy-no-etherscan.ts
- test/contracts/bond/erc20-single-collateral-bond.test.ts
- test/contracts/bond/single-collateral-multi-reward-bond.test.ts
- test/event/bond/single-collateral-bond-events.ts
- test/event/bond/verify-single-collateral-bond-events.ts
- test/framework/contracts.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/265
> feat: switching event token symbols to the address

- contracts/bond/BondCurator.sol
- contracts/bond/BondFactory.sol
- contracts/bond/BondMediator.sol
- contracts/bond/DaoBondCollateralWhitelist.sol
- contracts/bond/ERC20SingleCollateralBond.sol
- contracts/bond/RoleAccessControl.sol
- contracts/bond/RoleMembership.sol
- contracts/bond/TimeLockMultiRewardBond.sol
- test/contracts/bond/bond-curator.test.ts
- test/contracts/bond/bond-factory.test.ts
- test/contracts/bond/dao-bond-collateral-whitelist.test.ts
- test/contracts/bond/erc20-single-collateral-bond.test.ts
- test/contracts/bond/single-collateral-multi-reward-bond.test.ts
- test/contracts/bond/time-lock-multi-reward-bond.test.ts
- test/event/bond/bond-creator-events.ts
- test/event/bond/bond-curator-events.ts
- test/event/bond/bond-portal-events.ts
- test/event/bond/single-collateral-bond-events.ts
- test/event/bond/time-lock-multi-reward-bond-events.ts
- test/event/bond/verify-bond-creator-events.ts
- test/event/bond/verify-curator-events.ts
- test/event/bond/verify-single-collateral-bond-events.ts
- test/event/bond/verify-time-lock-multi-reward-bond-events.ts
- test/event/bond/verify-whitelist-events.ts
- test/event/bond/whitelist-events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/245
> feat: event parameter for instigator

- contracts/bond/MetaDataStore.sol
- test/contracts/bond/erc20-single-collateral-bond.test.ts
- test/event/bond/meta-data-store-events.ts
- test/event/bond/verify-meta-data-store-events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/274
> feat: set meta data event

- contracts/bond/Redeemable.sol
- test/contracts/bond/erc20-single-collateral-bond.test.ts
- test/event/bond/redeemable-events.ts
- test/event/bond/verify-redeemable-events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/275
> feat: redeemable event

- contracts/bond/DaoBondConfiguration.sol
- test/contracts/bond/dao-bond-configuration.test.ts
- test/event/bond/dao-bond-configuration-events.ts
- test/event/bond/verify-dao-bond-configuration-events.ts
- test/event/bond/verify-redeemable-events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/278
> feat set treasury event

- contracts/sweep/SweepERC20.sol
> fix: removing unused import

- contracts/bond/BondCurator.sol
- contracts/bond/BondFactory.sol
- contracts/bond/BondMediator.sol
- contracts/bond/ERC20SingleCollateralBond.sol
- contracts/bond/RoleMembership.sol
- contracts/bond/SingleCollateralBond.sol
- contracts/sweep/SweepERC20.sol
- contracts/sweep/TokenSweep.sol
- test/contracts/bond/bond-curator.test.ts
- test/contracts/bond/bond-factory.test.ts
- test/contracts/bond/bond-mediator.test.ts
- test/contracts/bond/erc20-single-collateral-bond.test.ts
- test/event/bond/verify-redeemable-events.ts
- test/event/sweep/sweep-erc20-events.ts
- test/event/sweep/token-sweeo-events.ts
- test/event/sweep/verify-sweep-erc20-events.ts
- test/event/sweep/verify-token-sweep-events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/258
> feat: ERC20 token sweep

- contracts/bond/DaoBondConfiguration.sol
- contracts/bond/MetaDataStore.sol
- contracts/bond/TimeLockMultiRewardBond.sol
- test/contracts/bond/dao-bond-configuration.test.ts
- test/contracts/bond/erc20-single-collateral-bond.test.ts
- test/contracts/bond/single-collateral-multi-reward-bond.test.ts
- test/event/bond/dao-bond-configuration-events.ts
- test/event/bond/meta-data-store-events.ts
- test/event/bond/time-lock-multi-reward-bond-events.ts
- test/event/bond/verify-dao-bond-configuration-events.ts
- test/event/bond/verify-meta-data-store-events.ts
- test/event/bond/verify-time-lock-multi-reward-bond-events.ts
> feat: consistent event names for state changes

- contracts/bond/ERC20SingleCollateralBond.sol
- test/contracts/bond/erc20-single-collateral-bond.test.ts
- test/contracts/bond/single-collateral-multi-reward-bond.test.ts
- test/event/bond/single-collateral-bond-events.ts
- test/event/bond/verify-single-collateral-bond-events.ts
closes https://github.com/windranger-io/windranger-treasury/issues/266
> fix: also verifying the event log for Bond events

- test/contracts/bond/erc20-single-collateral-bond.test.ts
closes https://github.com/windranger-io/windranger-treasury/issues/306
> fix: consistent variable naming

- contracts/bond/DaoBondCollateralWhitelist.sol
Adds daoId to whitelist collateral events
> feat: adds daoId to whitelist collateral events

- test/contracts/bond/dao-bond-collateral-whitelist.test.ts
- test/event/bond/verify-whitelist-events.ts
- test/event/bond/whitelist-events.ts
closes https://github.com/windranger-io/windranger-treasury/issues/312
Also adding in verifying of the event log
> fix: collateral whitelist ut to include dao id

- contracts/bond/TimeLockMultiRewardBond.sol
- test/contracts/bond/bond-factory.test.ts
- test/framework/contracts.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/262
> fix: ut for passing through reward pools

- test/contracts/bond/bond-curator.test.ts
- test/contracts/bond/bond-factory.test.ts
- test/event/bond/bond-creator-events.ts
- test/event/bond/verify-bond-creator-events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/315
> fix: ut event log verification for bond creator

- test/contracts/bond/bond-mediator.test.ts
- test/event/bond/bond-mediator-events.ts
- test/event/bond/verify-bond-mediator-events.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/316
> fix: event and event log verification for dao creation

- test/contracts/bond/bond-curator.test.ts
- test/event/bond/verify-bond-creator-events.ts
- test/event/bond/verify-bond-mediator-events.ts
- test/event/bond/verify-curator-events.ts
- test/event/bond/verify-dao-bond-configuration-events.ts
- test/event/bond/verify-meta-data-store-events.ts
- test/event/bond/verify-redeemable-events.ts
- test/event/bond/verify-single-collateral-bond-events.ts
- test/event/bond/verify-time-lock-multi-reward-bond-events.ts
- test/event/bond/verify-whitelist-events.ts
- test/event/sweep/verify-sweep-erc20-events.ts
- test/event/sweep/verify-token-sweep-events.ts
- test/framework/verify.ts
closes https://github.com/windranger-io/windranger-treasury/issues/317
> fix: standard parameter ordering

- test/event/bond/verify-bond-creator-events.ts
- test/event/bond/verify-bond-mediator-events.ts
- test/event/bond/verify-curator-events.ts
- test/event/bond/verify-dao-bond-configuration-events.ts
- test/event/bond/verify-meta-data-store-events.ts
- test/event/bond/verify-redeemable-events.ts
- test/event/bond/verify-single-collateral-bond-events.ts
- test/event/bond/verify-time-lock-multi-reward-bond-events.ts
- test/event/bond/verify-whitelist-events.ts
- test/framework/event-logs.ts
- test/framework/verify.ts
closes https://github.com/windranger-io/windranger-treasury/issues/320
> fix: further abstraction of the event test code for easier use

- test/event/bond/verify-bond-creator-events.ts
- test/event/bond/verify-bond-mediator-events.ts
- test/event/bond/verify-curator-events.ts
- test/event/bond/verify-dao-bond-configuration-events.ts
- test/event/bond/verify-meta-data-store-events.ts
- test/event/bond/verify-redeemable-events.ts
- test/event/bond/verify-single-collateral-bond-events.ts
- test/event/bond/verify-time-lock-multi-reward-bond-events.ts
- test/event/bond/verify-whitelist-events.ts
- test/framework/events.ts
- test/framework/verify.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/283
> feat: meaningful verify meessages

- test/contracts/staking/staking-factory.test.ts
- test/contracts/staking/staking.test.ts
resolves https://github.com/windranger-io/windranger-treasury/issues/332
> remove unused imports

- contracts/staking/StakingPool.sol
> change state view mutability of _calculateRewardAmount()

- .eslintrc
- docs/deploy_remote.md
- hardhat.config.ts
- scripts/deploy/bond-deploy.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/271
> feat: optional remote deploy with env vars

- README.md
- package-lock.json
- package.json
Closes https://github.com/windranger-io/windranger-treasury/issues/92
> feat: removing PlantUML due to unrelible downloading

- docs/deploy_local.md
- docs/deploy_remote.md
- scripts/deploy/bitdao-deploy-no-etherscan.ts
- scripts/deploy/deploy-all-no-etherscan.ts
> feat: executable bitdao token deploy and doco update

- docs/deploy_local.md
- scripts/deploy/bitdao-deploy-no-etherscan.ts
- scripts/deploy/bond-deploy-no-etherscan.ts
- scripts/deploy/bond-deploy.ts
- scripts/utils/contract.ts
Closes https://github.com/windranger-io/windranger-treasury/issues/341
> fix: script update to log the transaction id for contract deployment

- contracts/performance-bonds/ERC20SingleCollateralPerformanceBond.sol
- contracts/performance-bonds/TimeLockMultiRewardPerformanceBond.sol
- contracts/sweep/SweepERC20.sol
> feat: use safeERC20 for transfer and transferFrom

- contracts/staking/StakingPoolFactory.sol
- test/contracts/staking/staking-factory.test.ts
> feat: use constructor in staking pool factory

- scripts/deploy/deploy-all.ts
- scripts/deploy/staking-pool-deploy-no-etherscan.ts
two fixes: 
- import correct deploy WITH verify
- pass tokenSweepBeneficiary to staking-pool-deploy-no-etherscan staking pool factory constructor (was originally initializer)
> fix: deploy scripts

- contracts/staking/StakingPool.sol
- test/contracts/staking/staking.test.ts
as per https://github.com/windranger-io/windranger-treasury/issues/356
> fix: enforceUniqueRewardTokens

- contracts/staking/StakingPoolMediator.sol
- test/contracts/staking/staking-mediator.test.ts
- test/event/staking/staking-mediator-events.ts
- test/event/staking/verify-staking-mediator-events.ts
There was previously no way to set the dao's metadata
> bugfix: add setMetadata() to StakingPoolMediator

- contracts/staking/StakingPoolFactory.sol
- scripts/deploy/deploy-all.ts
- test/contracts/staking/staking-factory.test.ts
- test/contracts/staking/staking-mediator.test.ts
- test/event/staking/staking-factory-events.ts
- test/event/staking/verify-staking-factory-events.ts
> fix: emit config object

- contracts/staking/StakingPool.sol
- test/contracts/staking/staking.test.ts
as per https://github.com/windranger-io/windranger-treasury/issues/372
> fix: add min total stake checks
