contracts/bond/Bond.sol
docs/specs/bonding.puml
test/bond.test.ts
test/utils/events.ts

The only option available for Alice to know when her bond has reach full collateralization is by polling.
This PR adds an event that is emitted when the final deposit is made, reaching full collateral.

feat: emit event when full collateral has been reached

---

.gitignore
.lintstagedrc
.prettierrc
README.md
docs/specs/images/bonding-0.svg
docs/specs/images/escrow-0.svg
package.json
scripts/plantuml.mjs

Generating SVG files from PlantUML documents.
The script was based off the Treasury one, however it's been expanded to support both single file entires and a recursive search generating for all found (depending on the input) ...it's not an ironclad script, so users still have to beware (you could re-generate docs a number of times).

feat: render PlantUML as SVG

---

contracts/bond/Bond.sol

Fixing lint identified issue with '^0.8.2' being used.
```
Different versions of Solidity is used:
- Version used: ['>=0.4.22<0.9.0', '^0.8.0', '^0.8.2']
- ^0.8.0 (node_modules/@openzeppelin/contracts/access/Ownable.sol#3)
- ^0.8.0 (node_modules/@openzeppelin/contracts/security/Pausable.sol#3)
- ^0.8.0 (node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol#3)
- ^0.8.0 (node_modules/@openzeppelin/contracts/token/ERC20/IERC20.sol#3)
- ^0.8.0 (node_modules/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol#3)
- ^0.8.0 (node_modules/@openzeppelin/contracts/utils/Context.sol#3)
- ^0.8.2 (contracts/bond/Bond.sol#2)
- ^0.8.0 (contracts/bond/BondFactory.sol#2)
- >=0.4.22<0.9.0 (node_modules/hardhat/console.sol#2)
Reference: …
```

fix: common Solidity pragma

---

contracts/bond/Bond.sol
contracts/bond/BondFactory.sol

Fixes the following minor issues flagged by Slither:
```
Bond.constructor(string,string,address,address).treasury_ (contracts/bond/Bond.sol#78) lacks a zero-check on :
- _treasury = treasury_ (contracts/bond/Bond.sol#82)
Bond.setTreasury(address).treasury_ (contracts/bond/Bond.sol#227) lacks a zero-check on :
- _treasury = treasury_ (contracts/bond/Bond.sol#228)
BondFactory.constructor(address,address).securityToken_ (contracts/bond/BondFactory.sol#25) lacks a zero-check on :
- _collateralToken = securityToken_ (contracts/bond/BondFactory.sol#26)
BondFactory.constructor(address,address).treasury_ (contracts/bond/BondFactory.sol#25) lacks a zero-check on :
- _treasury = treasury_ (contracts/bond/BondFactory.sol#27)
BondFactory.setTreasury(address).treasury_ …
```

fix: zero address check on parameters

---

contracts/bond/Bond.sol
contracts/bond/BondFactory.sol

Refactoring variable naming, which also solving these issues flagged by Slither
```
Variable Bond._collateralToken (contracts/bond/Bond.sol#70) is too similar to Bond.constructor(string,string,address,address).collateralToken_ (contracts/bond/Bond.sol#77)
Variable BondFactory._collateralToken (contracts/bond/BondFactory.sol#22) is too similar to BondFactory.setCollateralToken(address).collateralToken_ (contracts/bond/BondFactory.sol#75)
Variable BondFactory._collateralToken (contracts/bond/BondFactory.sol#22) is too similar to BondFactory.constructor(address,address).collateralToken_ (contracts/bond/BondFactory.sol#25)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#variable-names-are-too-similar
```

fix: plural names for token contracts

---

contracts/bond/BondFactory.sol

Variable name too similar
```
Variable BondFactory._collateralTokens (contracts/bond/BondFactory.sol#22) is too similar to BondFactory.setCollateralTokens(address).collateralTokens_ (contracts/bond/BondFactory.sol#75)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#variable-names-are-too-similar
```

fix: variance in variable name

---

contracts/bond/Bond.sol
contracts/bond/BondFactory.sol

Fixes Slither lint issue about re-entrancy
```
Reentrancy in BondFactory.createBond(uint256,string,string) (contracts/bond/BondFactory.sol#38-55):
External calls:
- bond.mint(debtTokens) (contracts/bond/BondFactory.sol#44)
- bond.transferOwnership(owner()) (contracts/bond/BondFactory.sol#45)
Event emitted after the call(s):
- BondCreated(address(bond),name,symbol,bond.owner(),bond.treasury()) (contracts/bond/BondFactory.sol#46-52)
Reentrancy in Bond.redeem(uint256) (contracts/bond/Bond.sol#167-195):
External calls:
- transferred = _collateralTokens.transfer(_msgSender(),redemptionAmount) (contracts/bond/Bond.sol#182-185)
Event emitted after the call(s):
- Redemption(_msgSender(),symbol(),amount,_collateralTokens.symbol(),redemptionAmount) (contracts/bond/Bond.sol#188-194)
Reentrancy in …
```

fix: check-effects-interaction on emitted events

---

contracts/bond/Bond.sol
test/bond.test.ts

Having a guard on the withdrawal prevents using it in emergency conditions, or when there was partial collateral (e.g. bond expiry).

fix: allowing emergency flushing of funds from Bond

---

.github/workflows/master-push-pull.yml

As caching isn't working on the first run due to race condition, making the jobs sequential _should_ solve this.
Despite the jobs running concurrently, they bottleneck with only one at a time progressing to install

ci: sequential job execution

---

contracts/bond/Bond.sol

Decision to not allowing the setting of the collateral tokens was intentional, it has the potential to break the Bond operations / state.

docs: why collateral tokens is not settable

---

.github/workflows/master-push-pull.yml

Jobs were made sequential to ensure to creation of the common cache they all share (race condition, when all of them were parallel). However only one need to run first to ensure the cache creation, the remainder can be parallel.

ci: parallel after cache creation

---

contracts/bond/Bond.sol
contracts/bond/BondFactory.sol
package-lock.json
package.json
test/bond-factory.test.ts
test/bond.test.ts
test/utils/events.ts

Converting the Bond contract over to using an init function, instead of the constructor for initialisation.
While this is the groundwork for upgradability (if deployed with a proxy), it also can facilitate cloning. When deployed from a contract (i.e. BondContract) additional care would be needed if using a proxy pattern (due to proxy ownership behaviour).
Closes https://github.com/windranger-io/windranger-treasury/issues/15

feat: init function

---

contracts/bond/Bond.sol
test/bond.test.ts
test/utils/events.ts

In the use case of a bond receiving some it's expected collateral (but not all), the guarantors must be able to redeem their full deposit once it is released by the owner.
Fixes a bug where the in the partial collateral case, the guarantor were not receiving their full deposits (cause by the total supply number used in the calculation of redemption ratio).

fix: partial collateral, full redemption of deposit

---

.solhint.json
contracts/bond/Bond.sol
contracts/bond/BondFactory.sol
contracts/bond/ExpiryTimestamp.sol
contracts/test/Box.sol
test/bond-factory.test.ts
test/bond.test.ts

Bumped up the Solhint warning to errors to enforce code style in the Solidity (Solidity specific style, beyond the general Prettier-Solidity plugin)

fix: Solhint enforced Solidity styling

---

contracts/bond/Bond.sol

This saves on making a transfer, when redeeming if there is no value to transfer (`uint amount == 0`).
It bring the behaviour inline with the Bond's guards against trying to deposit, redeem or slash zero amounts, while also saving the gas cost for a guarantor who redeems and will get back none of their collateral (due to slashing). 
In theory, preventing a transfer when the value is zero also avoids the risk of interacting with the ERC20 contract who's behaviour is to revert in that case.

fix: no collateral transfer when amount is zero

---

package.json

The OZ contract are only required during the build phase. After contract compilation (generation of the deployable byte code) they are not required.

fix: OZ contracts as dev dependencies

---

contracts/bond/Bond.sol

Realised the explanation for redemption ration was sub-par, as it confused myself on re-reading.

fix: documentation update for redemption ratio

---

contracts/test/Box.sol

No underscores in parameter names.

fix: aligning parameter name with convention

---

.github/dependabot.yml
renovate.json

Replacing Dependabot for Renovate to have a single PR raised, instead of one per a changed dependency.

ci: renovate instead of dependabot for npm

---

.github/workflows/main-push-pull.yml
README.md
slither.json

The Slither CI task now uses the npm cache and takes the settings form the `slither.json` config file (instead of cmd line)

ci: slither config file with npm caching

---

contracts/bond/BondFactory.sol
contracts/bond/BondManager.sol
contracts/bond/BondMediator.sol
contracts/bond/Roles.sol
scripts/bond/create-bond.ts
scripts/bond/deploy.ts
test/bond-factory.test.ts
test/contracts/bond/bond-factory-events.ts
test/contracts/bond/verify-bond-factory-events.ts

Splits admins into four types:
1. DAO: role for all other admin roles
2. SysAdmin: allowed to upgrade contracts
3. Bond Aggregator: allowed to add bonds to the manager
4. Bond: ever previous Owner function.
Closes https://github.com/windranger-io/windranger-treasury/issues/162

feat: Multiple admin support

---

package.json

The single quotes break the script on both Powershell and Terminal, changing to remove the single quotes has them working across Windows and MacOs (zsh)

fix: scripting change support for windows

---

test/contracts/bond/bond-creator-events.ts
test/contracts/bond/bond-curator-events.ts
test/contracts/bond/single-collateral-bond-events.ts
test/contracts/bond/verify-bond-creator-events.ts
test/contracts/bond/verify-curator-events.ts
test/contracts/bond/verify-single-collateral-bond-events.ts
test/erc20-single-collateral-bond.test.ts

Mixed example are only going to cause confusion, converting all over to using typed parameter and return objects instead of anonymous types.
Motivation for explicitly typing is easier to read signatures and it better leverages TS (generally lower maintenance)

fix: typing anonymous parameters

---

contracts/bond/BondCreator.sol
contracts/bond/BondFactory.sol
contracts/bond/BondIdentity.sol
contracts/bond/BondMediator.sol
contracts/bond/BondSettings.sol
test/bond-factory.test.ts
test/bond-manager.test.ts
test/bond-mediator.test.ts
test/erc20-single-collateral-bond.test.ts

Part of one of the multi-stage implementation of https://github.com/windranger-io/windranger-treasury/issues/161
Moving the `treasury` address from the `BondFactory` , which is going to be a single instance (agnostic to the DAO Id) into the `BondMediator` that will be holding all the DAO configs.

feat: treasury from factory to mediator

---

contracts/bond/BondCreator.sol
contracts/bond/BondFactory.sol
contracts/bond/BondMediator.sol
test/bond-factory.test.ts
test/bond-manager.test.ts
test/bond-mediator.test.ts
test/erc20-single-collateral-bond.test.ts

Second part of the refactoring to implement https://github.com/windranger-io/windranger-treasury/issues/161
By moving collateral check into the mediator, the factor is now, or can be DAO ID agnostic.

fix: moving collateral whitelist to BondMediator

---

contracts/bond/BondMediator.sol
contracts/bond/DaoBondConfiguration.sol
test/bond-mediator.test.ts

When a `DAO_CREATOR` creates a DAO, by default they have no access, where in reality they should be a `DAO_ADMIN` for that DAO.
A `SUPER_USER` has no restriction and can do anything, anywhere 🙂

feat: granting dao admin roles to creators their daos

---

contracts/bond/BondCurator.sol
contracts/bond/BondMediator.sol
test/bond-curator.test.ts
test/contracts/bond/bond-curator-events.ts
test/contracts/bond/verify-curator-events.ts

Adding back the event that outputs the bond address and dao Id that it belongs to.

feat: Add bond event

---

.gitignore
README.md
hardhat.config.ts
package-lock.json
package.json

Follows on from https://github.com/windranger-io/windranger-treasury/pull/325
Instead of checking the auto gen docs in, this PR creates a target that the developer can run locally (where the generated directory is excluded via gitignore)

fix: auto generation of natspec markdown from Solidity files

---

contracts/bond/TimeLockMultiRewardBond.sol
contracts/staking/StakingPool.sol
test/contracts/bond/time-lock-multi-reward-bond.test.ts
test/contracts/staking/staking.test.ts

Close ticket #330, replacing the quadratic check of duplicated tokens for rewards with a linear check. Is minor but might appear on future audits.
It was passing all the tests and I added 1 more test for each contract I changed.

replacing quadratic check with linear

---

docs/deploy_local.md
docs/deploy_remote.md
scripts/deploy/deploy-all-no-etherscan.ts
scripts/deploy/deploy-all.ts
scripts/deploy/staking-pool-deploy-no-etherscan.ts
scripts/deploy/staking-pool-deploy.ts
scripts/utils/transaction-event-log.ts
scripts/verify/create-bond-dao.ts
scripts/verify/create-dao.ts
scripts/verify/create-managed-bond.ts
scripts/verify/create-staking-pool-dao.ts
scripts/verify/create-staking-pool.ts
scripts/verify/whitelist-bond-collateral.ts
scripts/verify/whitelist-collateral.ts
scripts/verify/whitelist-staking-pool-collateral.ts

feat: add staking pool deploy script

---

contracts/staking/StakingPoolMediator.sol
docs/deploy_local.md
docs/deploy_remote.md
scripts/utils/environment-variable.ts
scripts/verify/create-dao.ts
scripts/verify/create-staking-pool-dao.ts
test/contracts/staking/staking-mediator.test.ts

as per https://github.com/windranger-io/windranger-treasury/issues/359

feat: call setMetadata() in createDao()
